/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Docs */
        get: operations["list_docs_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Doc */
        delete: operations["delete_doc_documents__doc_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Document
         * @description TASK-015: 사용자가 자동 분류 결과를 수정. 인증 미도입 단계라 로컬 LAN 전용.
         */
        patch: operations["patch_document_documents__doc_id__patch"];
        trace?: never;
    };
    "/index/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index Overview
         * @description 빈 채팅 empty state용 — 현재 인덱싱된 문서들의 요약 + 예시 질문 5개.
         *     문서 목록 변동 없으면 인메모리 캐시 사용 (LLM 반복 호출 방지).
         */
        get: operations["index_overview_index_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description TASK-014: 문서 요약 조회. 미생성이면 summary=null 로 반환.
         */
        get: operations["get_summary_documents__doc_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/summary/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Summary
         * @description TASK-014: 동기 강제 재생성. 인증 미도입 단계라 로컬 LAN 전용으로 사용.
         */
        post: operations["regenerate_summary_documents__doc_id__summary_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Chunks
         * @description 관리자 UI용 청크 미리보기 — Qdrant payload scroll로 상위 N개 반환.
         */
        get: operations["preview_chunks_documents__doc_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_conversations__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_conversations__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingest Jobs */
        get: operations["list_ingest_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingest Job */
        get: operations["get_ingest_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Series */
        get: operations["list_all_series_series_get"];
        put?: never;
        /** Create One */
        post: operations["create_one_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_series__series_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete One
         * @description 시리즈 삭제. FK ON DELETE SET NULL로 멤버 documents.series_id는 NULL로 분리됨.
         */
        delete: operations["delete_one_series__series_id__delete"];
        options?: never;
        head?: never;
        /** Update One */
        patch: operations["update_one_series__series_id__patch"];
        trace?: never;
    };
    "/series/{series_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_series__series_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/_review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description auto_attached + suggested 두 큐 일람 — 관리자 검수용.
         */
        get: operations["review_queue_series__review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/series_match/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Match
         * @description auto_attached → confirmed (관리자가 자동 묶기를 확정).
         */
        post: operations["confirm_match_documents__doc_id__series_match_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/series_match/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Match
         * @description auto_attached/suggested → rejected (분리 + 동일 휴리스틱 재바인딩 차단).
         */
        post: operations["reject_match_documents__doc_id__series_match_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/series_match/attach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach Manual
         * @description 수동 묶기 — 관리자가 시리즈를 직접 지정. status=confirmed로 마킹.
         */
        post: operations["attach_manual_documents__doc_id__series_match_attach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_ingest_ingest_post */
        Body_ingest_ingest_post: {
            /** File */
            file: string;
            /** Title */
            title: string;
            /**
             * Source
             * @default
             */
            source: string;
            /** Doc Type */
            doc_type?: string | null;
            /** Category */
            category?: string | null;
            /** Tags */
            tags?: string | null;
        };
        /** ChunkPreview */
        ChunkPreview: {
            /** Chunk Index */
            chunk_index?: string | null;
            /**
             * Heading Path
             * @default []
             */
            heading_path: string[];
            /** Page */
            page?: number | null;
            /**
             * Content Type
             * @default text
             */
            content_type: string;
            /** Content */
            content: string;
        };
        /** ChunkPreviewResponse */
        ChunkPreviewResponse: {
            /** Doc Id */
            doc_id: string;
            /** Total Previewed */
            total_previewed: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkPreview"][];
        };
        /** ConversationDetail */
        ConversationDetail: {
            /** Session Id */
            session_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["MessageItem"][];
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationSummary"][];
            /** Total */
            total: number;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Session Id */
            session_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CreateConversationRequest */
        CreateConversationRequest: {
            /**
             * Title
             * @default
             */
            title: string | null;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Doc Id */
            doc_id: string;
            /** Deleted */
            deleted: boolean;
        };
        /** DocumentItem */
        DocumentItem: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** File Type */
            file_type: string;
            /** Chunk Count */
            chunk_count: number;
            /** Has Tables */
            has_tables: boolean;
            /** Has Images */
            has_images: boolean;
            /** Indexed At */
            indexed_at: string;
            /** Status */
            status: string;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Summary Model */
            summary_model?: string | null;
            /** Summary Generated At */
            summary_generated_at?: string | null;
            /**
             * Doc Type
             * @default book
             */
            doc_type: string;
            /** Category */
            category?: string | null;
            /** Category Confidence */
            category_confidence?: number | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Series Id */
            series_id?: string | null;
            /** Series Title */
            series_title?: string | null;
            /** Volume Number */
            volume_number?: number | null;
            /** Volume Title */
            volume_title?: string | null;
            /**
             * Series Match Status
             * @default none
             */
            series_match_status: string;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentItem"][];
            /** Total */
            total: number;
        };
        /**
         * DocumentPatchRequest
         * @description TASK-015: 사용자 메타데이터 수정용. 모두 optional, None은 'no-op'.
         */
        DocumentPatchRequest: {
            /** Doc Type */
            doc_type?: string | null;
            /** Category */
            category?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexOverviewResponse */
        IndexOverviewResponse: {
            /** Doc Count */
            doc_count: number;
            /** Titles */
            titles: string[];
            /** Top Headings */
            top_headings: string[];
            /** Summary */
            summary: string;
            /** Suggested Questions */
            suggested_questions: string[];
            /**
             * Top Tags
             * @default []
             */
            top_tags: string[];
            /**
             * Categories
             * @default []
             */
            categories: {
                [key: string]: unknown;
            }[];
            /**
             * Recent Docs
             * @default []
             */
            recent_docs: components["schemas"]["RecentDocItem"][];
        };
        /** IngestResponse */
        IngestResponse: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Chunk Count */
            chunk_count: number;
            /** Has Tables */
            has_tables: boolean;
            /** Has Images */
            has_images: boolean;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /** Job Id */
            job_id?: number | null;
        };
        /** JobItem */
        JobItem: {
            /** Id */
            id: number;
            /** Doc Id */
            doc_id?: string | null;
            /** Title */
            title: string;
            /**
             * Source
             * @default
             */
            source: string;
            /** Status */
            status: string;
            /** Retry Count */
            retry_count: number;
            /** Error */
            error?: string | null;
            /** Enqueued At */
            enqueued_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobItem"][];
            /** Total */
            total: number;
        };
        /** MessageItem */
        MessageItem: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
            /**
             * Session Id
             * @description 대화 세션 ID. 없으면 새 세션이 생성됩니다.
             */
            session_id?: string | null;
            /** Top K */
            top_k?: number | null;
            /** Score Threshold */
            score_threshold?: number | null;
            /**
             * Doc Filter
             * @description TASK-016: 특정 doc_id에 한정해 검색. 도서관 탭의 '이 책에 대해 묻기'.
             */
            doc_filter?: string | null;
            /**
             * Category Filter
             * @description TASK-019: 특정 카테고리(`payload.metadata.category`)에 한정해 검색. 상단 카테고리 칩·도서관 카테고리 [이 카테고리에 묻기].
             */
            category_filter?: string | null;
            /**
             * Series Filter
             * @description TASK-020 (ADR-029): 특정 series_id에 한정해 검색. 도서관 시리즈 카드 [이 시리즈에 대해 묻기]. doc_filter > category_filter 보다 후순위.
             */
            series_filter?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Session Id */
            session_id: string;
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["SourceItem"][];
            /** Latency Ms */
            latency_ms: number;
            /**
             * Suggestions
             * @default []
             */
            suggestions: string[];
        };
        /**
         * RecentDocItem
         * @description TASK-017: 랜딩 카드용 최근 문서 미니 정보.
         */
        RecentDocItem: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** One Liner */
            one_liner?: string | null;
            /** Category */
            category?: string | null;
        };
        /** SeriesCreateRequest */
        SeriesCreateRequest: {
            /** Series Id */
            series_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Cover Doc Id */
            cover_doc_id?: string | null;
            /**
             * Series Type
             * @default book
             */
            series_type: string;
        };
        /**
         * SeriesItem
         * @description TASK-020 (ADR-029): 시리즈/묶음 1급 시민 응답 모델.
         */
        SeriesItem: {
            /** Series Id */
            series_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Cover Doc Id */
            cover_doc_id?: string | null;
            /**
             * Series Type
             * @default book
             */
            series_type: string;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /** Created At */
            created_at: string;
        };
        /** SeriesListResponse */
        SeriesListResponse: {
            /** Series */
            series: components["schemas"]["SeriesItem"][];
            /** Total */
            total: number;
        };
        /** SeriesMembersResponse */
        SeriesMembersResponse: {
            /** Series Id */
            series_id: string;
            /** Members */
            members: components["schemas"]["DocumentItem"][];
        };
        /** SeriesPatchRequest */
        SeriesPatchRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Cover Doc Id */
            cover_doc_id?: string | null;
            /** Series Type */
            series_type?: string | null;
        };
        /**
         * SeriesReviewItem
         * @description auto_attached + suggested 검수 큐 항목.
         */
        SeriesReviewItem: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** Series Id */
            series_id?: string | null;
            /** Series Title */
            series_title?: string | null;
            /** Volume Number */
            volume_number?: number | null;
            /** Series Match Status */
            series_match_status: string;
        };
        /** SourceItem */
        SourceItem: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** Page */
            page?: number | null;
            /**
             * Content Type
             * @default text
             */
            content_type: string;
            /** Score */
            score: number;
            /** Excerpt */
            excerpt: string;
        };
        /**
         * SummaryResponse
         * @description TASK-014: 문서 요약 조회/재생성 응답.
         */
        SummaryResponse: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Summary Model */
            summary_model?: string | null;
            /** Summary Generated At */
            summary_generated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_docs_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
        };
    };
    delete_doc_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_document_documents__doc_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_overview_index_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexOverviewResponse"];
                };
            };
        };
    };
    get_summary_documents__doc_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_summary_documents__doc_id__summary_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_chunks_documents__doc_id__chunks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
        };
    };
    create_conversation_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_conversations__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_conversations__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingest_jobs_jobs_get: {
        parameters: {
            query?: {
                /** @description pending|in_progress|done|failed|cancelled */
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingest_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_series_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesListResponse"];
                };
            };
        };
    };
    create_one_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_series__series_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_one_series__series_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_one_series__series_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_series__series_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesMembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_series__review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesReviewItem"][];
                };
            };
        };
    };
    confirm_match_documents__doc_id__series_match_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_match_documents__doc_id__series_match_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_manual_documents__doc_id__series_match_attach_post: {
        parameters: {
            query: {
                series_id: string;
                volume_number?: number | null;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
